<a href="https://colab.research.google.com/github/sherylsqin/CE888/blob/master/Lab5/my_recommender.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import pandas as pd
import numpy as np

In [0]:
df1 = pd.read_csv("https://raw.githubusercontent.com/albanda/CE888/master/lab5-recommender/jester-data-1.csv",header=None)
df1



0      1      2      3      4    ...    96     97     98     99     100
0       74  -7.82   8.79  -9.66  -8.16  ...  99.00  -5.63  99.00  99.00  99.00
1      100   4.08  -0.29   6.36   4.37  ...  -2.14   3.06   0.34  -4.32   1.07
2       49  99.00  99.00  99.00  99.00  ...  99.00  99.00  99.00  99.00  99.00
3       48  99.00   8.35  99.00  99.00  ...  99.00  99.00  99.00  99.00  99.00
4       91   8.50   4.61  -4.17  -5.39  ...   1.55   3.11   6.55   1.80   1.60
...    ...    ...    ...    ...    ...  ...    ...    ...    ...    ...    ...
24978  100   0.44   7.43   9.08   2.33  ...   9.03   6.55   8.69   8.79   7.43
24979   91   9.13  -8.16   8.59   9.08  ...  -8.20  -7.23  -8.59   9.13   8.45
24980   39  99.00  99.00  99.00  99.00  ...  99.00  99.00  99.00  99.00  99.00
24981   37  99.00  99.00  99.00  99.00  ...  99.00  99.00  99.00  99.00  99.00
24982   72   2.43   2.67  -3.98   4.27  ...  99.00  99.00  99.00  99.00  99.00

[24983 rows x 101 columns]

In [0]:
df = df1.drop(df.columns[0], axis=1)  
df

1      2      3      4     5    ...    96     97     98     99     100
0      -7.82   8.79  -9.66  -8.16 -7.52  ...  99.00  -5.63  99.00  99.00  99.00
1       4.08  -0.29   6.36   4.37 -2.38  ...  -2.14   3.06   0.34  -4.32   1.07
2      99.00  99.00  99.00  99.00  9.03  ...  99.00  99.00  99.00  99.00  99.00
3      99.00   8.35  99.00  99.00  1.80  ...  99.00  99.00  99.00  99.00  99.00
4       8.50   4.61  -4.17  -5.39  1.36  ...   1.55   3.11   6.55   1.80   1.60
...      ...    ...    ...    ...   ...  ...    ...    ...    ...    ...    ...
24978   0.44   7.43   9.08   2.33  3.20  ...   9.03   6.55   8.69   8.79   7.43
24979   9.13  -8.16   8.59   9.08  0.87  ...  -8.20  -7.23  -8.59   9.13   8.45
24980  99.00  99.00  99.00  99.00 -7.77  ...  99.00  99.00  99.00  99.00  99.00
24981  99.00  99.00  99.00  99.00 -9.71  ...  99.00  99.00  99.00  99.00  99.00
24982   2.43   2.67  -3.98   4.27 -2.28  ...  99.00  99.00  99.00  99.00  99.00

[24983 rows x 100 columns]

In [0]:
arr = df.values
print(arr.shape)

(24983, 100)


In [0]:
rated = np.where(arr!=99)
print(len(rated[0]), rated[1].shape)

1810455 (1810455,)


In [0]:
def replace(orig, percentage=0.1):
  """
  Replaces 'percentage'% of the original values in 'orig' with 99's
  :param orig: original data array
  :param percentage: percentage of values to replace (0<percentage<1)
  """
  new_data = orig.copy()
  rated = np.where(arr!=99)
  n_rated = len(rated[0])
  idx = np.random.choice(n_rated, size=int(percentage*n_rated), replace=False)
  new_data[rated[0][idx], rated[1][idx]] = 99
  return new_data, (rated[0][idx], rated[1][idx])

In [0]:

new_arr, idx = replace(arr, 0.1)

In [0]:
arr[idx[0][0], idx[1][0]]

-1.07

In [0]:
[idx[0][0], idx[1][0]]

[2013, 4]

In [0]:
n_latent_factors = 5

user_ratings = df.values
# Initialise as random values
latent_user_preferences = np.random.random((user_ratings.shape[0], n_latent_factors))
latent_item_features = np.random.random((user_ratings.shape[1], n_latent_factors))

In [0]:
latent_item_features


array([[3.26273829e-01, 8.19088953e-01, 7.22512512e-02, 7.02449669e-01,
        4.60709748e-01],
       [5.51144873e-01, 2.90572015e-01, 8.32231677e-01, 8.40968599e-01,
        7.35788051e-01],
       [3.60722749e-01, 5.39251872e-01, 7.14316894e-01, 9.14383759e-01,
        5.45756904e-01],
       [8.58953025e-01, 4.42449152e-01, 1.97781980e-01, 6.15071330e-01,
        8.19825530e-01],
       [6.09994151e-01, 5.01069646e-01, 9.39297305e-01, 9.78079426e-02,
        4.64790414e-01],
       [8.76924186e-01, 2.27816541e-02, 9.96211860e-02, 3.57320382e-01,
        4.76200133e-01],
       [5.15054406e-01, 1.80336242e-01, 1.21657561e-01, 4.17507390e-01,
        8.40589986e-03],
       [2.15482983e-01, 8.10897996e-01, 7.01073339e-01, 8.01459794e-01,
        4.39506081e-01],
       [1.37237261e-01, 4.42242880e-01, 4.89724904e-01, 7.06662841e-01,
        2.89099111e-01],
       [1.66368214e-01, 8.53781254e-01, 4.58793739e-01, 2.17382834e-01,
        1.15202955e-02],
       [2.36441882e-01, 9.3742

In [0]:
latent_user_preferences

array([[0.19104624, 0.87543874, 0.23654393, 0.9577274 , 0.36138008],
       [0.60585889, 0.25772021, 0.59260203, 0.20097521, 0.72618169],
       [0.9497148 , 0.03469013, 0.61046351, 0.43324543, 0.53277098],
       ...,
       [0.69368299, 0.09239655, 0.63398831, 0.6086099 , 0.7736255 ],
       [0.69141055, 0.12268258, 0.77251446, 0.80399187, 0.52894063],
       [0.82436348, 0.9474875 , 0.48329322, 0.71423944, 0.47716791]])

In [0]:
def predict_rating(user_id, item_id):
    """ Predict a rating given a user_id and an item_id.
    """
    user_preference = latent_user_preferences[user_id]
    item_preference = latent_item_features[item_id]
    return user_preference.dot(item_preference)


def train(user_id, item_id, rating, alpha=0.0001):
    
    #print item_id
    prediction_rating = predict_rating(user_id, item_id)
    err =  prediction_rating - rating
    #print err
    user_pref_values = latent_user_preferences[user_id][:]
    latent_user_preferences[user_id] -= alpha * err * latent_item_features[item_id]
    latent_item_features[item_id] -= alpha * err * user_pref_values
    return err
    

def sgd(iterations=70):
    """ Iterate over all users and all items and train for 
        a certain number of iterations
    """
    for iteration in range(iterations):
        error = []
        for user_id in range(latent_user_preferences.shape[0]):
            for item_id in range(latent_item_features.shape[0]):
                rating = user_ratings[user_id][item_id]
                if rating != 99:
                    err = train(user_id, item_id, rating)
                    error.append(err)
        mse = (np.array(error) ** 2).mean()   
        if (iteration % 10) == 0:
            print(mse)

In [0]:
sgd()


25.56022434965629
23.842896477802565
19.152893479779745
17.625953942465113
17.35866332069358
17.1134262497944
16.763316672433575


In [0]:
idx

(array([ 2013, 16755,     8, ..., 12831, 23338, 12720]),
 array([ 4, 61, 79, ...,  3, 53, 30]))

In [0]:
len(idx[1])

181045

In [0]:
#for i in range(0, len(idx[0])):
  #for j in range(0, len(idx[1])):
    #print(idx[0][i], idx[1][j])

In [0]:
idx[0][0], idx[1][0]

(2013, 4)

In [0]:
n_latent_factors = 5

# Initialise as random values
ilatent_user_preferences = np.random.random((useri_ratings.shape[0], n_latent_factors))
ilatent_item_features = np.random.random((useri_ratings.shape[1], n_latent_factors))

AttributeError: ignored

In [0]:
def predict_rating(user_id, item_id):
    """ Predict a rating given a user_id and an item_id.
    """
    user_preference = ilatent_user_preferences[user_id]
    item_preference = ilatent_item_features[item_id]
    return user_preference.dot(item_preference)


def train(user_id, item_id, rating, alpha=0.0001):
    
    #print item_id
    prediction_rating = predict_rating(user_id, item_id)
    err =  prediction_rating - rating
    #print err
    user_pref_values = latent_user_preferences[user_id][:]
    latent_user_preferences[user_id] -= alpha * err * latent_item_features[item_id]
    latent_item_features[item_id] -= alpha * err * user_pref_values
    return err
    

def sgd(iterations=70):
    """ Iterate over all users and all items and train for 
        a certain number of iterations
    """
    for iteration in range(iterations):
        error = []
        for user_id in range(latent_user_preferences.shape[0]):
            for item_id in range(latent_item_features.shape[0]):
                rating = user_ratings[user_id][item_id]
                if rating != 99:
                    err = train(user_id, item_id, rating)
                    error.append(err)
        mse = (np.array(error) ** 2).mean()
           
        if (iteration % 10) == 0:
            print(mse)

In [0]:
predictions = latent_user_preferences.dot(latent_item_features.T)
predictions

array([[ 9.75933367e+01,  6.24729593e+00,  3.51736780e+00, ...,
         4.81565762e-01,  1.77866956e+00,  1.80636204e+00],
       [ 4.91357207e+01,  5.69819276e+00,  5.52220418e+00, ...,
         7.18406683e+00,  8.57571922e+00,  7.39450174e+00],
       [ 4.78576617e+01,  3.30268161e+00,  4.22241029e+00, ...,
         3.32053926e+00,  2.14928202e-01,  4.34685065e+00],
       ...,
       [ 3.90981462e+01,  2.18511434e-01, -3.23822391e-01, ...,
        -3.07319613e-01, -7.67384268e-01, -8.63939592e-02],
       [ 3.78278290e+01, -1.58063964e+00, -1.40335411e+00, ...,
        -5.30760733e-02, -1.13669986e+00, -2.53053508e-01],
       [ 7.20346281e+01,  1.99417846e+00,  2.33112033e+00, ...,
         4.27816555e+00,  3.15330366e+00,  4.41479590e+00]])

In [0]:
values = [zip(user_ratings[i], predictions[i]) for i in range(predictions.shape[0])]
comparison_data = pd.DataFrame(values)
comparison_data.columns = df.columns

In [0]:
comparison_data


74  ...                         99.25
0       (100.0, 97.5933366711837)  ...    (1.07, 1.8063620369268063)
1       (49.0, 49.13572070167389)  ...     (99.0, 7.394501740216275)
2       (48.0, 47.85766170727544)  ...     (99.0, 4.346850649000992)
3       (91.0, 90.76002190414205)  ...     (1.6, 4.6982826906143025)
4      (100.0, 99.12636264532205)  ...   (-3.45, -5.178059144605095)
...                           ...  ...                           ...
24977  (100.0, 99.96138325407829)  ...     (7.43, 5.080056921918106)
24978   (91.0, 88.96804859440884)  ...    (8.45, 0.1582961864989096)
24979  (39.0, 39.098146203820676)  ...  (99.0, -0.08639395921370169)
24980   (37.0, 37.82782900924459)  ...   (99.0, -0.2530535075742692)
24981   (72.0, 72.03462810488924)  ...     (99.0, 4.414795898365327)

[24982 rows x 101 columns]